### ISSUE TITLE
v2/Documents/Download Returns DocumentListItem instead of filename if unauthorized

### ISSUE THREAD

**Issue by nrshapiro** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#60]
On a document download request, if it's unauthorized, instead of returning an error, the API library returns the Solr results (abstract, etc.) and the server tries to return that in the filename field.

When authorized to download, the return is correct.

The server should return a 401 error instead in this case.

(reported by @lhorne-gavant )

**Comment by billdami** [comment]
@nrshapiro I did not realize you were no longer relying on cookies to authenticate these download requests (in discussions w/ @adistasio in the past, he mentioned you still intended to have cookies set on the api/pads domains). Since we are not initiating these download requests in-javascript via ajax/fetch (to circumvent issues with handling files in-memory), we cannot set the session ID header like we can for normal API requests.

Do you have an alternate means of authenticating these downloads? Usually in this case you either have to do it via cookies, or by adding a param to the url that takes the user's session ID, e.g. `GET /v2/Documents/Downloads/PDF/IJP.077.0217A/?SessionID={string}`

**Comment by nrshapiro** [comment]
@billdami - ok, the 9/28 release on stage supports client-session and client-id from
- the header , but if not found:
   - the query parameters, but if not found,
       - a cookie, named client-session and client-id respectively.

**Comment by billdami** [comment]
Thanks @nrshapiro. So just to confirm the format, the query param based method would be:
```
GET /v2/Documents/Downloads/PDF/IJP.077.0217A/?client-id=2&client-session=ABC-123
```

**Comment by nrshapiro** [comment]
yes. it should work like that!

**Comment by nrshapiro** [comment]
@billdami 

I tested that in Postman and I had a prerequest script sticking the client-session in the header, so my test was invalid.  There was a naming issue with the variables...fixed in a version I will upload to stage shortly (if it passes the general tests...working on a few things as you'll see in the Changelog https://github.com/Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server/wiki/OpenPubArchive-Content-Server-CHANGELOG.md

**Comment by nrshapiro** [comment]
Should work in the latest 2020.0929.1 build on stage.  Close when confirmed.

Original document return in filename is fixed as well.  I can't seem to get the PaDS authorization in Postman to work to confirm right now though, so leaving it open.

**Comment by adistasio** [comment]
@nrshapiro This has been updated on stage however the download still doesn't work with an error of 

`{"detail":"No permission for document The requested document None could not be returned."}`

https://stage-api.pep-web.rocks/v2/Documents/Downloads/EPUB/IJP.077.0217A/?client-id=2&client-session=REDACTED

**Comment by adistasio** [comment]
@nrshapiro  This has been updated on stage however the download still doesn't work with an error of

{"detail":"No permission for document The requested document None could not be returned."}

/v2/Documents/Downloads/EPUB/IJP.077.0217A/?client-id=2&client-session=REDACTED

**Comment by nrshapiro** [comment]
@adistasio 

Well the error was only when you weren't authorized, so that had nothing to do with it.  It's always been working, BUT perhaps you weren't sending over client-id=2 (which was required to check with PaDS in that code before...but I removed that anyway in the last rebuild, since today I completely switched the API over to PaDS authentication and thus all my tests had to be converted to using PaDS and logging in via PaDS.  And I just tested it on your client (since I loaded that version to Stage) and it works fine for downloads.

However, I actually had to put it on stage without testing with the Stage data because apparently after the last database/solr/schema load, the IPs changed, and I must be blacklisted again...I can get to stage-solr interactively, but if I set my local copy of the server to try to connect there (which is how I test with the remote data), it can't connect to Solr anymore.  (So I just went ahead an pushed the version without testing with that data (which I like to do first).  

Perhaps you can look into whitelisting me again.  but that's another topic, as far as I can tell, this issue is closed...
