### ISSUE TITLE
IP and User calls to PaDS

### ISSUE THREAD

**Issue by jwoosnam** [Psychoanalytic-Electronic-Publishing/OpenPubArchive-Content-Server#76]
We are currently getting several IP and user calls per minute from your server to the PaDS API. This is not a problem as such I just wanted to know if they were necessary, and whether they were going to continue when we go into production.
They seem to go in sets of 4, an IP call to create the session, then a user call with the new session ID, then another IP call with the new session ID and finally a user call.  Then after a short time it starts again.

**Comment by nrshapiro** [comment]
I'm not running calls at the moment.  Working on something else. Haven't run one for at least an hour, maybe more.

**Comment by jwoosnam** [comment]
It looks like it is from the production server as they have the same IP address (3.91.86.77) as permit calls coming from David and Paul.
<img width="1130" alt="Screenshot 2020-12-12 at 11 09 33" src="https://user-images.githubusercontent.com/70103034/101982274-99d4eb80-3c6a-11eb-905d-aac1b8c4514f.png">

**Comment by nrshapiro** [comment]
@adistasio 

I'm not sure about these yet, but it may be related to something polling the server directly on the production server, whereas I don't see it on stage.  It looks like all night, every few seconds, I am getting requests with no client ID.  No client ID requests are assigned 666 for devilish reasons.  (Though the OpenAPI document interface does not supply a client ID in requests, so that shows up too as 666 unless you set a cookie for client id.  

![image](https://user-images.githubusercontent.com/4837554/101988466-c2a7b180-3c67-11eb-94a7-618bb031e173.png)

These functions happen automatically with API calls that have client and session id parameters.  (The "tick" call api_status does not have these.)

This is wasting session ids too, and PaDS bandwidth.  I may have to stop asking for a session ID for requests without a client ID (or with client ID 666).  That would mean the OpenAPI doc would require that you set a cookie for the client ID, since it's possible that's how these requests are coming in, though they could also be coming in directly. 

Perhaps it's Google or some indexer hitting this?

I've added a log item to see the nature of the request coming in.

**Comment by jwoosnam** [comment]
Thanks for the update.  
It would be good to get this sorted, there were 35,000 anonymous IP and user of calls over the weekend. There were only 145 calls from logged-on users!

**Comment by lhorne-gavant** [comment]
@nrshapiro  @jwoosnam I've updated the firewall for production. The issue should be resolved now but please let me know if you see any other issues.

**Comment by jwoosnam** [comment]
@lhorne-gavant I am not sure how the firewall would affect this, but the number of calls coming through has NOT reduced.

**Comment by nrshapiro** [comment]
@adistasio 
@lhorne-gavant  - yes, we're still getting hit every few seconds.  See the production console for stdout.

```
2020-12-14T09:41:43.893-05:00 | 2020-12-14 14:41:43 main/get_client_session(231): INFO Client 666 request w/o sessionID: http://172.30.1.90/v2/Session/Status/'
-- | --
  | 2020-12-14T09:41:43.893-05:00 | 2020-12-14 14:41:43 opasDocPermissions/get_authserver_session_userinfo(248): INFO Non-logged in user for client-id 666 sessionId: 47b3245f-4eef-49f6-b371-bf34054fff4e. Info from PaDS: SessionId has not been successfully logged on, so user details can't be retrieved.
  | 2020-12-14T09:41:43.893-05:00 | 2020-12-14 14:41:43 opasDocPermissions/get_authserver_session_info(224): INFO ***authent: False - get_full_session_info total time: 0.05286002159118652***
  | 2020-12-14T09:41:44.143-05:00 | 2020-12-14 14:41:43 libs.opasAPISupportLib/get_session_info(287): INFO Session 47b3245f-4eef-49f6-b371-bf34054fff4e not found. Getting from authserver (will save on server)
  | 2020-12-14T09:41:44.143-05:00 | 2020-12-14 14:41:43 opasDocPermissions/get_authserver_session_userinfo(248): INFO Non-logged in user for client-id 666 sessionId: 47b3245f-4eef-49f6-b371-bf34054fff4e. Info from PaDS: SessionId has not been successfully logged on, so user details can't be retrieved.
  | 2020-12-14T09:41:44.143-05:00 | 2020-12-14 14:41:43 opasDocPermissions/get_authserver_session_info(224): INFO ***authent: False - get_full_session_info total time: 0.05238676071166992***
  | 2020-12-14T09:41:44.143-05:00 | 2020-12-14 14:41:43 libs.opasAPISupportLib/get_session_info(301): INFO getSessionInfo: session_id='47b3245f-4eef-49f6-b371-bf34054fff4e' user_id=0 username='NotLoggedIn' is_valid_login=False has_subscription=False is_valid_username=False authenticated=False confirmed_unauthenticated=True authorized_peparchive=False authorized_pepcurrent=False session_start=datetime.datetime(2020, 12, 13, 19, 11, 55, 26825) session_end=None session_expires_time=datetime.datetime(2020, 12, 20, 19, 11, 54, 26825) user_type='Unknown' admin=False api_client_id=666 pads_session_info=PadsSessionInfo(HasSubscription=False, IsValidLogon=False, IsValidUserName=False, ReasonId=200, SessionExpires=604799, SessionId='47b3245f-4eef-49f6-b371-bf34054fff4e', session_start_time=datetime.datetime(2020, 12, 13, 19, 11, 55, 26825), pads_status_response=200, pads_disposition=None, ReasonStr='') pads_user_info=None
  | 2020-12-14T09:41:50.073-05:00 | 2020-12-14 14:41:43 root/raw(833): INFO solrpy request: q=art_id:APA.009.0331A&fl=art_id,+art_vol,+art_year,score&version=2.2&wt=xml
  | 2020-12-14T09:42:06.160-05:00 | 2020-12-14 14:42:06 main/get_client_session(231): INFO Client 666 request w/o sessionID: http://172.30.1.90/v2/Session/Status/' 
-- | --
```

**Comment by lhorne-gavant** [comment]
@jwoosnam I had assumed that number of calls would be coming from bots, but that was not the case here. The production healthcheck endpoint has been updated and I no longer see the extra calls in the api logs. Thanks for the heads up!

**Comment by jwoosnam** [comment]
@lhorne-gavant Sorted!!  The last call in the log file was 2020-12-14 14:49:14.647 GMT
